In [1]:
import numpy as np
import time

In [2]:
# 1. Array Creation
array_1d = np.array([10, 20, 30, 40, 50])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
print("1D Array:", array_1d)

1D Array: [10 20 30 40 50]


In [6]:
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [9]:
# 2. Indexing and Slicing
print("First element:", array_1d[0])

First element: 10


In [10]:
print("Slice (index 1 to 3):", array_1d[1:4])

Slice (index 1 to 3): [20 30 40]


In [11]:
print("2D element:", array_2d[1, 2])

2D element: 6


In [12]:
# 3. Mathematical Operations
print("Addition:", array_1d + 5)

Addition: [15 25 35 45 55]


In [13]:
print("Multiplication:", array_1d * 2)

Multiplication: [ 20  40  60  80 100]


In [14]:
# 4. Statistical Operations
print("Mean:", np.mean(array_1d))

Mean: 30.0


In [15]:
print("Median:", np.median(array_1d))

Median: 30.0


In [16]:
print("Standard Deviation:", np.std(array_1d))

Standard Deviation: 14.142135623730951


In [17]:
print("Sum:", np.sum(array_1d))

Sum: 150


In [18]:
# 5. Axis-wise Operations
print("Column Sum:", np.sum(array_2d, axis=0))

Column Sum: [5 7 9]


In [19]:
print("Row Sum:", np.sum(array_2d, axis=1))

Row Sum: [ 6 15]


In [21]:
# 6. Reshaping
reshaped = array_1d.reshape(5, 1)

In [22]:
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[10]
 [20]
 [30]
 [40]
 [50]]


In [23]:
# 7. Broadcasting
broadcast_result = array_2d + np.array([10, 20, 30])

In [24]:
print("Broadcasting Result:\n", broadcast_result)

Broadcasting Result:
 [[11 22 33]
 [14 25 36]]


In [25]:
# 8. Save and Load NumPy Array
np.save("data_saved.npy", array_1d)

In [26]:
loaded_array = np.load("data_saved.npy")

In [27]:
print("Loaded Array:", loaded_array)

Loaded Array: [10 20 30 40 50]


In [28]:
# 9. Performance Comparison
size = 1000000

In [29]:
python_list = list(range(size))

In [30]:
numpy_array = np.arange(size)

In [32]:
start = time.time()
python_sum = sum(python_list)
end = time.time()

In [33]:
print("Python List Sum Time:", end - start)

Python List Sum Time: 0.016541004180908203


In [34]:
start = time.time()
numpy_sum = np.sum(numpy_array)
end = time.time()

In [35]:
print("NumPy Array Sum Time:", end - start)

NumPy Array Sum Time: 0.003280162811279297
